// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.960
package views

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "time"
import "github.com/tikimcrzx723/alejandrinasweb/internal/api"
import "context"
import "github.com/tikimcrzx723/alejandrinasweb/routes/contexts"

func getAllCategories() map[int]string {
	categories, err := api.GetAllCategories(context.Background(), "http://localhost:8080/api/v1")
	if err != nil {
		return nil
	}

	var categoryNames = make(map[int]string)
	for _, category := range categories.Categories {
		categoryNames[category.ID] = category.Name
	}

	return categoryNames
}

func navigation() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<!--====== Preloader Part Start ======--><div class=\"preloader\"><div class=\"loader\"><div class=\"ytp-spinner\"><div class=\"ytp-spinner-container\"><div class=\"ytp-spinner-rotator\"><div class=\"ytp-spinner-left\"><div class=\"ytp-spinner-circle\"></div></div><div class=\"ytp-spinner-right\"><div class=\"ytp-spinner-circle\"></div></div></div></div></div></div></div><!--====== Preloader Part Ends ======--><!--====== Navbar Style 7 Part Start ======--><div class=\"navigation\"><header class=\"menu-style-7 position-relative\"><div class=\"navbar-container navbar-sidebar-7\"><!-- navbar top Start --><div class=\"navbar-top-wrapper\"><div class=\"container-lg\"><div class=\"navbar-top d-flex justify-content-between\"><!-- navbar top left Start --><div class=\"navbar-top-left\"><ul class=\"navbar-top-link\"><li class=\"d-none d-md-block\"><a href=\"#0\"><i class=\"mdi mdi-phone-in-talk\"></i>+502-3196-7779</a></li></ul></div><!-- navbar top left Ends --><div class=\"navbar-top-right\"><ul class=\"navbar-top-link\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if contexts.ExtractApp(ctx).IsAuthenticated {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<li><a href=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var2 templ.SafeURL
			templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinURLErrs(templ.SafeURL("/logout"))
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `views/base.templ`, Line: 68, Col: 57}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "\"><i class=\"mdi mdi-account\"></i>Cerrar Sesión</a></li>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			if contexts.ExtractApp(ctx).Role == "admin" {
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "<li><a href=\"")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				var templ_7745c5c3_Var3 templ.SafeURL
				templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinURLErrs(templ.SafeURL("/admin/dashboard/product/register"))
				if templ_7745c5c3_Err != nil {
					return templ.Error{Err: templ_7745c5c3_Err, FileName: `views/base.templ`, Line: 72, Col: 85}
				}
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "\"><i class=\"mdi mdi-account\"></i>Admin</a></li>")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
		} else {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, "<li><a href=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var4 templ.SafeURL
			templ_7745c5c3_Var4, templ_7745c5c3_Err = templ.JoinURLErrs(templ.SafeURL("/login"))
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `views/base.templ`, Line: 77, Col: 56}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var4))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 7, "\"><i class=\"mdi mdi-account\"></i>Iniciar Sesión</a></li><li><a href=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var5 templ.SafeURL
			templ_7745c5c3_Var5, templ_7745c5c3_Err = templ.JoinURLErrs(templ.SafeURL("/register"))
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `views/base.templ`, Line: 80, Col: 59}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var5))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 8, "\"><i class=\"mdi mdi-account\"></i>Crear cuenta</a></li>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 9, "</ul></div></div></div></div><!-- navbar top Ends --><!-- main navbar Start --><div class=\"navbar-wrapper\"><div class=\"container-lg\"><nav class=\"main-navbar d-lg-flex justify-content-between align-items-center\"><!-- desktop logo Start --><div class=\"desktop-logo d-lg-block\"><a href=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var6 templ.SafeURL
		templ_7745c5c3_Var6, templ_7745c5c3_Err = templ.JoinURLErrs(templ.SafeURL("/"))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `views/base.templ`, Line: 98, Col: 45}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var6))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 10, "\"><img src=\"/static/images/logos/alejandrinas_logo.svg\" width=\"96px\" alt=\"Logo\"></a></div><!-- desktop logo Ends --><div class=\"navbar-menu-toggle d-lg-block\"><button id=\"toggle-menu-6\" class=\"menu-toggle\"><span class=\"toggle-icon\"></span> <span class=\"toggle-icon\"></span> <span class=\"toggle-icon\"></span></button></div><!-- navbar menu Start --><div class=\"navbar-menu\"><ul class=\"main-menu\"><div class=\"navbar-close d-lg-none text-right mb-3\"><a href=\"#0\" id=\"menu-close\"><i class=\"mdi mdi-close\"></i></a></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		for _, category := range getAllCategories() {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 11, "<li><a href=\"/category/{category}\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var7 string
			templ_7745c5c3_Var7, templ_7745c5c3_Err = templ.JoinStringErrs(category)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `views/base.templ`, Line: 119, Col: 66}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var7))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 12, "</a></li>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 13, "</ul></div><!-- navbar menu Ends --><div class=\"navbar-search-cart d-none d-lg-flex\"><!-- navbar search start --><div class=\"navbar-search search-style-5\"><div class=\"search-select\"><div class=\"select-position\"><select id=\"select26\"><option value=\"\" selected>All</option> ")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		for _, category := range getAllCategories() {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 14, "<option value=\"{category}\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var8 string
			templ_7745c5c3_Var8, templ_7745c5c3_Err = templ.JoinStringErrs(category)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `views/base.templ`, Line: 132, Col: 64}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var8))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 15, "</option>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 16, "</select></div></div><div class=\"search-input\"><input type=\"text\" placeholder=\"Search\"></div><div class=\"search-btn\"><button><i class=\"lni lni-search-alt\"></i></button></div></div><!-- navbar search Ends --><!-- navbar cart start --><!-- navbar cart Ends --></div></nav></div></div><!-- main navbar Ends --></div><div class=\"overlay-7\"></div></header></div><!--====== Navbar Style 7 Part Ends ======-->")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func base(title string) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var9 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var9 == nil {
			templ_7745c5c3_Var9 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 17, "<!doctype html><html lang=\"en\"><head><meta charset=\"utf-8\"><!--====== Title ======--><title>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var10 string
		templ_7745c5c3_Var10, templ_7745c5c3_Err = templ.JoinStringErrs(title)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `views/base.templ`, Line: 167, Col: 21}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var10))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 18, "</title><meta name=\"description\" content=\"\"><meta name=\"viewport\" content=\"width=device-width, initial-scale=1\"><meta property=\"og:title\" content=\"The Rock\"><meta property=\"og:image\" content=\"/static/images/logos/alejandrinas_logo.svg\"><script src=\"https://cdn.jsdelivr.net/npm/htmx.org@2.0.8/dist/htmx.min.js\"></script><!--====== Favicon Icon ======--><link rel=\"shortcut icon\" href=\"/static/images/logos/favicon.ico\" type=\"image/png\"><!--====== Slick CSS ======--><link rel=\"stylesheet\" href=\"/static/css/slick.css\"><!--====== Line Icons CSS ======--><link rel=\"stylesheet\" href=\"/static/css/LineIcons.css\"><!--====== Material Design Icons CSS ======--><link rel=\"stylesheet\" href=\"/static/css/materialdesignicons.min.css\"><!--====== Jquery Ui CSS ======--><link rel=\"stylesheet\" href=\"/static/css/jquery-ui.min.css\"><!--====== nice select CSS ======--><link rel=\"stylesheet\" href=\"/static/css/nice-select.css\"><!--====== Bootstrap CSS ======--><link rel=\"stylesheet\" href=\"/static/css/bootstrap.min.css\"><!--====== Default CSS ======--><link rel=\"stylesheet\" href=\"/static/css/default.css\"><!--====== Style CSS ======--><link rel=\"stylesheet\" href=\"/static/css/styles.css\"></head><body>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = navigation().Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templ_7745c5c3_Var9.Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = footer().Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 19, "<!--====== Bootstrap 5 js ======--><script src=\"/static/js/popper.min.js\"></script><script src=\"/static/js/bootstrap.min.js\"></script><!--====== Jquery js ======--><script src=\"/static/js/vendor/jquery-3.5.1.min.js\"></script><script src=\"/static/js/vendor/modernizr-3.7.1.min.js\"></script><!--====== Slick js ======--><script src=\"/static/js/slick.min.js\"></script><!--====== Accordion Steps Form js ======--><script src=\"/static/js/jquery-vj-accordion-steps.js\"></script><!--====== Jquery Ui js ======--><script src=\"/static/js/jquery-ui.min.js\"></script><!--====== Form validator js ======--><script src=\"/static/js/jquery.form-validator.min.js\"></script><!--====== nice select js ======--><script src=\"/static/js/jquery.nice-select.min.js\"></script><!--====== formatter js ======--><script src=\"/static/js/jquery.formatter.min.js\"></script><!--====== Main js ======--><script src=\"/static/js/count-up.min.js\"></script><!--====== Main js ======--><script src=\"/static/js/main.js\"></script><script src=\"/static/js/sweet-alert.js\"></script></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func footer() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var11 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var11 == nil {
			templ_7745c5c3_Var11 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 20, "<!--====== Footer Style 3 Part Start ======--><section class=\"footer-style-3 pt-100 pb-100\"><div class=\"container\"><div class=\"footer-top\"><div class=\"row justify-content-center\"><div class=\"col-lg-5 col-md-7 col-sm-10\"><div class=\"footer-logo text-center\"><a href=\"index.html\"><img src=\"/static/images/logos/alejandrinas_logo.svg\" width=\"128px\" alt=\"\"></a></div><h5 class=\"heading-5 text-center mt-30\">Siguenos en nuestras redes sociales</h5><ul class=\"footer-follow text-center\"><li><a href=\"javascript:void(0)\"><i class=\"lni lni-facebook-filled\"></i></a></li><li><a href=\"javascript:void(0)\"><i class=\"lni lni-instagram-original\"></i></a></li><li><a href=\"javascript:void(0)\"><i class=\"lni lni-whatsapp\"></i></a></li></ul></div></div></div><div class=\"footer-copyright text-center\"><p>Siempre las mejores ofertas &copy; ")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var12 string
		templ_7745c5c3_Var12, templ_7745c5c3_Err = templ.JoinStringErrs(time.Now().Format("2006-01-02"))
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `views/base.templ`, Line: 275, Col: 79}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var12))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 21, "</p></div></div></section><!--====== Footer Style 3 Part Ends ======-->")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
